### ISSUE TITLE
Many global hotkeys don't work

### ISSUE THREAD

**Issue by Cratesmith** [LaoDie1/godot-float-script-editor#4]
I really like this plugin, but I'm struggling to use it as lots of hotkeys don't seem to work when the window is floating.

It's mostly navigation hotkeys.
- Ctrl-shift-o and ctrl-alt-o open the file open dialog instead of the quick open dialogs (I assume this is because only ctrl-o is being recognized)
- Ctrl-F does work for find inside the window but ctrl-alt-f and ctrl-l for go to function and go to line don't.

I'm assuming there are others but these are the ones that are stopping me.

**Comment by LaoDie1** [comment]
Thanks for pointing out the problem, the above shortcut keys have been added
