### ISSUE TITLE
发布1.0.1 /1.1.0版本

### ISSUE THREAD

**Issue by mrbbbaixue** [LaoDie1/godot-float-script-editor#8]
- [x] 可以考虑发布一个Github Release，因为已经有很多新功能合入了。
- [x] 需要修改plugin.cfg的版本号
- [x] Godot Asset Library那边是不是也得操作一下。发布新版本？

**Comment by LaoDie1** [comment]
可以，不过我已经睡了😂，要不你帮忙发布一个新的版本，或者我明天发

**Comment by mrbbbaixue** [comment]
> 可以，不过我已经睡了😂，要不你帮忙发布一个新的版本，或者我明天发

我没有对这个仓库的写权限没法发2333。不过也不急啦，有空再弄。晚安🌙

**Comment by LaoDie1** [comment]
完成
